site_name: UL HPC Tutorials
pages:
- Home: 'index.md'
- Basic Tutorials:
  - Getting Started: 'basic/getting_started/index.md'
  - HPC workflow with sequential jobs: 'basic/sequential_jobs/index.md'
  - Efficient Debugging: 'advanced/Debug/README.md'
- Advanced Software Management:
  - Easybuild: 'advanced/EasyBuild/index.md'
  - RESIF: 'advanced/RESIF/README.md'
- MPI:
  - OSU Micro-benchmarks: 'advanced/OSU_MicroBenchmarks/index.md'
  - High Performance Linpack (HPL): 'advanced/HPL/index.md'
  - High Performance Conjugate Gradient (HPCG): 'advanced/HPCG/README.md'
- Mathematics:
  - MATLAB: 'advanced/MATLAB1/README.md'
  - R - statistical computing: 'advanced/R/index.md'
- Bioinformatics:
  - Running bioinformatics software: 'advanced/Bioinformatics/index.md'
  - Galaxy: 'advanced/Galaxy/README.md'
- Parallel Debuggers:
  - Allinea: 'advanced/Allinea/README.md'
  - TotalView: 'advanced/TotalView/README.md'
- Virtualization:
  - Vagrant: 'advanced/Vagrant/README.md'
  - Grid5000 - Automatic VM deployment with VM5K: 'advanced/vm5k/README.md'
- CFD/MD/Chemistry:
  - Advanced Parallel execution: 'advanced/ParallelExec/README.md'
- Advanced topics:
  - Advanced workflows on sequential jobs management: 'advanced/advanced_workflows/README.md'
  - Advanced scheduling with SLURM: 'advanced/advanced_scheduling/index.md'
  - Big Data Application Over Apache Spark: 'advanced/Spark/index.md'
  - Prototyping with Python: 'advanced/Python/index.md'
- Documentation (RTFD): 'rtfd.md'
- Contributing: 'contributing.md'
- Contacts: 'contacts.md'
theme: readthedocs
